### ISSUE TITLE
page/HomePageFinalized

### ISSUE THREAD

**Issue by viss5vuus98** [Hexsnorth12/TicketSystem-frontend#54]
![Image](https://github.com/Hexsnorth12/TicketSystem-frontend/assets/101302525/dcb223fd-cf27-4b31-bff3-d35120ef80f5)

**Comment by muchuanhung** [comment]
- [ ] card button 要替換
- [ ] rwd要有手機 網頁要多-md
- [ ] card 也要增加swiper loop (熱門電影 & 一起揪團)

**Comment by muchuanhung** [comment]
第一項完成


![Image](https://github.com/Hexsnorth12/TicketSystem-frontend/assets/61078091/14c1c583-1ae6-4295-a5e7-b8eac7a7a1bd)
![Image](https://github.com/Hexsnorth12/TicketSystem-frontend/assets/61078091/c091f98c-29d7-469f-8ceb-b03548525c66)

**Comment by muchuanhung** [comment]
第二項完成
![Image](https://github.com/Hexsnorth12/TicketSystem-frontend/assets/61078091/4b45d9f5-1f46-4fce-bd27-e95dc84c68d8)
